### ISSUE TITLE
CA Certificate issues

### ISSUE THREAD

**Issue by erindru** [flathub/org.freedesktop.Sdk.Extension.openjdk8#5] opened 2019-05-16 21:29 UTC
Hello,

I believe that this version of OpenJDK is suffering from the [same issue reported here](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk10/issues/4).

I am getting the following error from Maven as it tries to download a dependency:
```
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty 
```

The reason I am using OpenJDK 8 instead of OpenJDK 11 is because I am trying to build [Spring Data JPA](https://github.com/spring-projects/spring-data-jpa) from within a [Flatpak'd Visual Studio Code](https://github.com/flathub/com.visualstudio.code), and it requires Java 8 to build. As far as I can tell the team does not yet support building on Java 11, and attempting to fails because [Java 11 removed a bunch of the Java EE classes](https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist) which Spring Data JPA depends on.

The issue logged against OpenJDK10 was apparently fixed in OpenJDK11, is there any chance it could be backported to OpenJDK8?

**Comment by MatMaul** [comment] 2019-05-29 09:42
This only package AdoptOpenJDK, feel free to ask a backport on there side, they have a mailing and a slack:
https://mail.openjdk.java.net/mailman/listinfo/adoption-discuss
https://www.adoptopenjdk.net/slack.html

I am closing, if you get what you need upstream feel free to reopen once the fix is out in a  release.

**Closed by MatMaul** 2019-05-29 09:42 UTC

**Comment by MatMaul** [comment] 2019-05-29 09:44
Do you know if AWS Corretto is fixed regarding your problem ? It was my second upstream option, if they deal better with this kind of problems we can switch to it.
https://github.com/corretto/corretto-8

**Comment by cxrvh** [comment] 2019-08-04 14:44
It's not an upstream issue, the problem doesn't exist with the AdaptOpenJDK builds (https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot, I tried Hotspot jdk8u212-b04 & jdk8u222-b10).

It's easily reproducible with Grails (3.3.10, https://grails.org/) since it already fails at `grails help`.

The keystore (`/usr/lib/sdk/openjdk8/jvm/java-8-openjdk/jre/lib/security/cacerts`) is empty and `p11-kit / trust` fail when extracting a new keystore (https://src.fedoraproject.org/rpms/ca-certificates/blob/master/f/update-ca-trust, use `-v` to print the error messages):

> p11-kit: couldn't load attributes: An error occurred on the device
> p11-kit: couldn't load attributes: An error occurred on the device
> …
